server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /disc/ {
        auth_basic "DISC";
        auth_basic_user_file /etc/nginx/.htpasswd;
        try_files $uri $uri/ /disc/index.html;
    }
}
